[build]
  command = "cd frontend/angular_portfolio && npm install && npm run build"
  publish = "frontend/angular_portfolio/dist/angular_portfolio/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200